title: South West UK Pre-CHI
preposition: ""
description: >-
  South West UK Pre-CHI provides an opportunity for researchers from the South West England and De Cymru Human-Computer Interaction Community (SWEDC-HCI) to come together to practice running their accepted CHI papers and work-in-progress research talks.
url: "https://South-West-UK-Pre-CHI.github.io"
favicon: "/assets/images/favicon.ico"

markdown: kramdown
sass:
  style: compressed

exclude:
  - vendor
  - .github/
  - README.md
  - LICENSE.md
  - REDISTRIBUTED.md
  - purgecss.config.js

collections:
  talks:
    output: true
    permalink: /:collection/:title/
  speakers:
    output: true
    permalink: /:collection/:title/
  rooms:
    output: true
    permalink: /:collection/:title/

defaults:
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
  - scope:
      path: ""
      type: speakers
    values:
      layout: speaker
  - scope:
      path: ""
      type: rooms
    values:
      layout: room

conference:
  lang: en
  tz: "+00:00"
  show_errors: true
  navigation:
    breakpoint: md
    links:
      # - name: Programme
      #  relative_url: /programme/
      #- name: Talks
      #  relative_url: /talks/
      #- name: Speakers
      #  relative_url: /speakers/
      #- name: Location
      #  relative_url: /location/
      # - name: Organisers
      #  relative_url: /organisers/
      - name: Previous Editions
        menu:
          - name: 2027 (current)
            disabled: true
          - name: 2026
            absolute_url: https://south-west-uk-pre-chi.github.io/2026
          - name: 2025
            absolute_url: https://south-west-uk-pre-chi.github.io/2025
          - name: 2024
            absolute_url: https://sites.google.com/view/southwestprechi/2024/paper-presentation-abstracts
  meta:
    link_preview:
      disable: true
  info:
    bars:
      - title: Planning for Pre-CHI 2027 is underway.
        color: secondary
        main_only: true
  talks:
    tracks:
      - name: Main Track
